### ISSUE TITLE
Help needed Sleet/Nuget.exe

### ISSUE THREAD

**Issue by WernerMairl** [emgarten/Sleet#23] opened 2017-11-12 05:53 UTC
Hi

I have created a (Sleet) azure feed (without sleet.exe but with sleetlib using dotnet core 2.0)
the feed should be available so anyone can inspect/reproduce that:
https://sitsfeed.blob.core.windows.net/sleet/index.json

using nuget.exe (in two different versions) i get always the same result:

command executed:
nuget.exe list -verbosity detailed -source https://sitsfeed.blob.core.windows.net/sleet/index.json

expected: a list of packages (there should be one package there)

Results:

NuGet Version: **4.3**.0.4406
WARNING: This version of nuget.exe does not support listing packages from package source 'https://sitsfeed.blob.core.windows.net/sleet/index.json'.
No packages found.

NuGet Version: **4.4**.0.4475
WARNING: This version of nuget.exe does not support listing packages from package source 'https://sitsfeed.blob.core.windows.net/sleet/index.json'.
No packages found.

inspecting the feed with a browser i can see:

index.json returns:

```
{"version":"3.0.0","sleet:version":"1.0.0","resources":[{"@id":"https://sitsfeed.blob.core.windows.net/sleet/sleet.settings.json","@type":"http://schema.emgarten.com/sleet#SettingsFile/1.0.0","comment":"Sleet feed settings."},{"@id":"https://sitsfeed.blob.core.windows.net/sleet/catalog/index.json","@type":"Catalog/3.0.0","comment":"Catalog service."},{"@id":"https://sitsfeed.blob.core.windows.net/sleet/autocomplete/query","@type":"SearchAutocompleteService/3.0.0-beta","comment":"Powershell autocomplete."},{"@id":"https://sitsfeed.blob.core.windows.net/sleet/search/query","@type":"SearchQueryService/3.0.0-beta","comment":"Static package list in search result form."},{"@id":"https://sitsfeed.blob.core.windows.net/sleet/sleet.packageindex.json","@type":"http://schema.emgarten.com/sleet#PackageIndex/1.0.0","comment":"Sleet package index."},{"@id":"https://sitsfeed.blob.core.windows.net/sleet/registration/","@type":"RegistrationsBaseUrl/3.4.0","comment":"Package registrations used for search and packages.config."},{"@id":"https://sitsfeed.blob.core.windows.net/sleet/","@type":"ReportAbuseUriTemplate/3.0.0","comment":"Report abuse template."},{"@id":"https://sitsfeed.blob.core.windows.net/sleet/flatcontainer/","@type":"PackageBaseAddress/3.0.0","comment":"Packages used by project.json"},{"@id":"https://sitsfeed.blob.core.windows.net/sleet/symbols/packages/index.json","@type":"http://schema.emgarten.com/sleet#SymbolsPackageIndex/1.0.0","comment":"Packages indexed in the symbols feed."},{"@id":"https://sitsfeed.blob.core.windows.net/sleet/symbols/","@type":"http://schema.emgarten.com/sleet#SymbolsServer/1.0.0","comment":"Symbols server containing dll and pdb files."}],"@context":{"@vocab":"http://schema.nuget.org/services#","sleet":"http://schema.emgarten.com/sleet#","comment":"http://www.w3.org/2000/01/rdf-schema#comment"}}

```

packages/index.json 
returns the expected package (one)

```
{"packages":{"SQLiteExtensions":["1.2.0"]},"symbols":{}}
```

I'm not able to see the problem. What i'm doing wrong ?

regards
Werner

**Comment by emgarten** [comment] 2017-11-12 07:05
You are doing it right, the problem is that there currently is no v3 protocol for list in nuget.exe. When listing packages on nuget.org the v3 url redirects to the older v2 url.

The workaround for this is to read the package index that sleet creates to discover packages. 
https://sitsfeed.blob.core.windows.net/sleet/sleet.packageindex.json

**Comment by emgarten** [comment] 2017-11-30 04:55
Closing this since I think it is answered. Let me know if you need anything else.

**Closed by emgarten** 2017-11-30 04:55 UTC

**Comment by jcagme** [comment] 2018-07-31 19:39
I'm trying to do the same but when I point to sleet.packageindex.json I get:

Unable to load the service index for source source/sleet.packageindex.json. The source does not have the 'version' property.

If I add a version to it (2.0.0, 3.0.0) I get the original error. Ideas?

**Comment by emgarten** [comment] 2018-08-03 15:47
@jcagme nuget.exe doesn't support sleet.packageindex.json, you need to point to index.json.

Are you also trying to list packages from a v3 feed?

**Comment by jcagme** [comment] 2018-08-03 16:32
Oh, I misread your comment:

> The workaround for this is to read the package index that sleet creates to discover packages.
https://sitsfeed.blob.core.windows.net/sleet/sleet.packageindex.json

So we'd have to implement something to process the file and return the list of packages in our feed, right?

> Are you also trying to list packages from a v3 feed?

Yes. A Sleet created feed

**Comment by emgarten** [comment] 2018-08-06 02:11
> So we'd have to implement something to process the file and return the list of packages in our feed, right?

Yes, that would be the easiest way. The file format of *sleet.packageindex.json* is trivial.

To fix this on the feed sleet would need to write out all packages in the v2 OData XML format.

Ideally this would be fixed by in nuget.exe by falling back to use v3 search to find all packages, or by adding support for a v3 list resource.
